import { NextRequest, NextResponse } from "next/server";

// Only manually verified facility matches and reusable photographs are published.
const photos = [
  {
    names: ["海遊館", "大阪海遊館"],
    category: "aquarium",
    photo: {
      url: "/place-photos/kaiyukan.webp",
      credit: "Sakai Yayoi / Wikimedia Commons",
      license: "CC0",
      license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes: "縮小・WebP変換",
      source_url: "https://commons.wikimedia.org/wiki/File:Kaiy%C5%ABkan.jpg",
    },
  },
  {"names": ["姫路城"], "category": "castle", "photo": {"url": "/place-photos/himeji.webp", "credit": "Loggieloggie / Wikimedia Commons", "license": "CC0", "license_url": "https://creativecommons.org/publicdomain/zero/1.0/", "source_url": "https://commons.wikimedia.org/wiki/File:Himeji_Castle_20260403120700.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["松本城"], "category": "castle", "photo": {"url": "/place-photos/matsumoto.webp", "credit": "Milion Base / Wikimedia Commons", "license": "CC0", "license_url": "https://creativecommons.org/publicdomain/zero/1.0/", "source_url": "https://commons.wikimedia.org/wiki/File:Matsumoto_Castle_2024.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["彦根城"], "category": "castle", "photo": {"url": "/place-photos/hikone.webp", "credit": "先従隗始 / Wikimedia Commons", "license": "CC0", "license_url": "https://creativecommons.org/publicdomain/zero/1.0/", "source_url": "https://commons.wikimedia.org/wiki/File:Hikone_Castle_20221113_02.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["犬山城"], "category": "castle", "photo": {"url": "/place-photos/inuyama.webp", "credit": "Z3144228 / Wikimedia Commons", "license": "CC BY-SA 4.0", "license_url": "https://creativecommons.org/licenses/by-sa/4.0/", "source_url": "https://commons.wikimedia.org/wiki/File:Inuyama_castle_front_gate.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["松江城"], "category": "castle", "photo": {"url": "/place-photos/matsue.webp", "credit": "Gmfrgsn (Greg Ferguson) / Wikimedia Commons", "license": "CC BY-SA 3.0", "license_url": "https://creativecommons.org/licenses/by-sa/3.0/", "source_url": "https://commons.wikimedia.org/wiki/File:MatsueCastle.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["弘前城"], "category": "castle", "photo": {"url": "/place-photos/hirosaki.webp", "credit": "掬茶 / Wikimedia Commons", "license": "CC BY-SA 4.0", "license_url": "https://creativecommons.org/licenses/by-sa/4.0", "source_url": "https://commons.wikimedia.org/wiki/File:Hirosaki_Castle_Keep_Tower_20220508.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["丸岡城"], "category": "castle", "photo": {"url": "/place-photos/maruoka.webp", "credit": "baku13 / Wikimedia Commons", "license": "CC BY-SA 2.1 jp", "license_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en", "source_url": "https://commons.wikimedia.org/wiki/File:Maruoka_Castle_20100529-01.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["備中松山城"], "category": "castle", "photo": {"url": "/place-photos/bitchu-matsuyama.webp", "credit": "by Reggaeman / Wikimedia Commons", "license": "CC BY-SA 3.0", "license_url": "http://creativecommons.org/licenses/by-sa/3.0/", "source_url": "https://commons.wikimedia.org/wiki/File:Bitchu_Matsuyama_Castle_1.JPG", "changes": "縮小・WebP変換"}},
  {"names": ["丸亀城"], "category": "castle", "photo": {"url": "/place-photos/marugame.webp", "credit": "Toto-tarou / Wikimedia Commons", "license": "CC BY-SA 3.0", "license_url": "https://creativecommons.org/licenses/by-sa/3.0", "source_url": "https://commons.wikimedia.org/wiki/File:Marugame_Castle01.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["松山城"], "category": "castle", "photo": {"url": "/place-photos/matsuyama.webp", "credit": "Masoud Akbari / Wikimedia Commons", "license": "CC BY-SA 3.0", "license_url": "https://creativecommons.org/licenses/by-sa/3.0", "source_url": "https://commons.wikimedia.org/wiki/File:Marunouchi,_Matsuyama,_Ehime_Prefecture_790-0008,_Japan_-_panoramio_(80).jpg", "changes": "縮小・WebP変換"}},
  {"names": ["宇和島城"], "category": "castle", "photo": {"url": "/place-photos/uwajima.webp", "credit": "Original uploader was Vickerman625 at en.wikipedia / Wikimedia Commons", "license": "Public domain", "license_url": "https://commons.wikimedia.org/wiki/Commons:Public_domain", "source_url": "https://commons.wikimedia.org/wiki/File:Uwajima-jo.JPG", "changes": "縮小・WebP変換"}},
  {"names": ["高知城"], "category": "castle", "photo": {"url": "/place-photos/kochi.webp", "credit": " / Wikimedia Commons", "license": "Public domain", "license_url": "https://commons.wikimedia.org/wiki/Commons:Public_domain", "source_url": "https://commons.wikimedia.org/wiki/File:Kouchi_kouchijou1.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["出雲日御碕灯台"], "category": "lighthouse", "photo": {"url": "/place-photos/hinomisaki.webp", "credit": "663highland / Wikimedia Commons", "license": "CC BY 2.5", "license_url": "https://creativecommons.org/licenses/by/2.5", "source_url": "https://commons.wikimedia.org/wiki/File:Hinomisaki_lighthouse_Izumo01bs3200.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["観音埼灯台"], "category": "lighthouse", "photo": {"url": "/place-photos/kannonzaki.webp", "credit": "椎林 隆夫 / Wikimedia Commons", "license": "CC BY-SA 3.0", "license_url": "https://creativecommons.org/licenses/by-sa/3.0", "source_url": "https://commons.wikimedia.org/wiki/File:Kannonzaki_Lighthouse_02.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["角島灯台"], "category": "lighthouse", "photo": {"url": "/place-photos/tsunoshima.webp", "credit": "藤谷良秀 / Wikimedia Commons", "license": "CC BY-SA 3.0", "license_url": "https://creativecommons.org/licenses/by-sa/3.0", "source_url": "https://commons.wikimedia.org/wiki/File:Tsunoshima_light_house_2012.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["潮岬灯台"], "category": "lighthouse", "photo": {"url": "/place-photos/shionomisaki.webp", "credit": "BUNBUN / Wikimedia Commons", "license": "CC BY-SA 2.1 jp", "license_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en", "source_url": "https://commons.wikimedia.org/wiki/File:Shionomisaki-lighthouse_Jul2006.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["犬吠埼灯台"], "category": "lighthouse", "photo": {"url": "/place-photos/inubosaki.webp", "credit": "Ippukucho / Wikimedia Commons", "license": "CC BY 3.0", "license_url": "https://creativecommons.org/licenses/by/3.0", "source_url": "https://commons.wikimedia.org/wiki/File:InubosakiLighthouse.JPG", "changes": "縮小・WebP変換"}},
  {"names": ["草津温泉"], "category": "hot-spring", "photo": {"url": "/place-photos/kusatsu.webp", "credit": "くろふね / Wikimedia Commons", "license": "CC BY-SA 4.0", "license_url": "https://creativecommons.org/licenses/by-sa/4.0", "source_url": "https://commons.wikimedia.org/wiki/File:%E8%8D%89%E6%B4%A5%E6%B8%A9%E6%B3%89%E3%81%AE%E6%B9%AF%E7%95%9103.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["有馬温泉"], "category": "hot-spring", "photo": {"url": "/place-photos/arima.webp", "credit": "663highland / Wikimedia Commons", "license": "CC BY 2.5", "license_url": "https://creativecommons.org/licenses/by/2.5", "source_url": "https://commons.wikimedia.org/wiki/File:170811_Rokko-Arima_Ropeway_Kobe_Japan00n.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["道後温泉"], "category": "hot-spring", "photo": {"url": "/place-photos/dogo.webp", "credit": "Arnaud Malon / Wikimedia Commons", "license": "CC BY 2.0", "license_url": "https://creativecommons.org/licenses/by/2.0", "source_url": "https://commons.wikimedia.org/wiki/File:D%C5%8Dgo_Onsen.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["下呂温泉"], "category": "hot-spring", "photo": {"url": "/place-photos/gero.webp", "credit": "663highland / Wikimedia Commons", "license": "CC BY-SA 4.0", "license_url": "https://creativecommons.org/licenses/by-sa/4.0", "source_url": "https://commons.wikimedia.org/wiki/File:260125_Gero_Onsen_Gero_Gifu_pref_Japan01s3.jpg", "changes": "縮小・WebP変換"}},
  {"names": ["鉄輪温泉"], "category": "hot-spring", "photo": {"url": "/place-photos/kannawa.webp", "credit": "松岡明芳 / Wikimedia Commons", "license": "CC BY-SA 4.0", "license_url": "https://creativecommons.org/licenses/by-sa/4.0", "source_url": "https://commons.wikimedia.org/wiki/File:2020-02-24_Kannawa_Onsen_%E9%89%84%E8%BC%AA%E6%B8%A9%E6%B3%89%E5%85%A8%E6%99%AF_DSCF8631.jpg", "changes": "縮小・WebP変換"}},
  {"names":["横浜美術館"],"category":"museum","photo":{"url":"/place-photos/yokohama-museum.webp","credit":"Kakidai / Wikimedia Commons","license":"CC BY-SA 4.0","license_url":"https://creativecommons.org/licenses/by-sa/4.0/","source_url":"https://commons.wikimedia.org/wiki/File:Yokohama_Museum_of_Art_2019.jpg","changes":"2019年撮影 · 縮小・WebP変換"}},
  {"names":["川崎市藤子・F・不二雄ミュージアム"],"category":"museum","photo":{"url":"/place-photos/fujiko-museum.webp","credit":"Aimaimyi / Wikimedia Commons","license":"CC BY-SA 3.0","license_url":"https://creativecommons.org/licenses/by-sa/3.0/","source_url":"https://commons.wikimedia.org/wiki/File:Fujiko%EF%BD%A5F%EF%BD%A5Fujio_Museum_-01.jpg","changes":"2011年撮影 · 縮小・WebP変換"}},
  {"names":["神奈川県立生命の星・地球博物館"],"category":"museum","photo":{"url":"/place-photos/earth-museum.webp","credit":"テレストレラッソ / Wikimedia Commons","license":"CC BY-SA 4.0","license_url":"https://creativecommons.org/licenses/by-sa/4.0/","source_url":"https://commons.wikimedia.org/wiki/File:KanagawaPrefecturalMuseumOfNaturalHistory-202504exterior.jpg","changes":"2025年撮影 · 縮小・WebP変換"}},
  {"names":["横須賀美術館"],"category":"museum","photo":{"url":"/place-photos/yokosuka-museum.webp","credit":"Banzai Hiroaki / Wikimedia Commons","license":"CC BY 2.0","license_url":"https://creativecommons.org/licenses/by/2.0/","source_url":"https://commons.wikimedia.org/wiki/File:Yokosuka_Museum_of_Art_20100709-02.jpg","changes":"2010年撮影 · 縮小・WebP変換"}},
  {"names":["平塚市美術館"],"category":"museum","photo":{"url":"/place-photos/hiratsuka-museum.webp","credit":"Dddeco / Wikimedia Commons","license":"CC BY 2.5","license_url":"https://creativecommons.org/licenses/by/2.5/","source_url":"https://commons.wikimedia.org/wiki/File:Hiratsuka_MOA.JPG","changes":"2008年撮影 · 縮小・WebP変換"}},
  {"names":["世田谷美術館"],"category":"museum","photo":{"url":"/place-photos/setagaya-art.webp","credit":"Wiiii / Wikimedia Commons","license":"CC BY-SA 3.0","license_url":"https://creativecommons.org/licenses/by-sa/3.0/","source_url":"https://commons.wikimedia.org/wiki/File:Setagaya_Art_Museum.jpg","changes":"2009年撮影 · 縮小・WebP変換"}},
  {"names":["大田区立郷土博物館"],"category":"museum","photo":{"url":"/place-photos/ota-folk.webp","credit":"Suikotei / Wikimedia Commons","license":"CC BY 4.0","license_url":"https://creativecommons.org/licenses/by/4.0/","source_url":"https://commons.wikimedia.org/wiki/File:Folk_Museum_of_Ota_City_20250713.jpg","changes":"2025年撮影 · 縮小・WebP変換"}},
  {"names":["杉並区立郷土博物館"],"category":"museum","photo":{"url":"/place-photos/suginami-history.webp","credit":"江戸村のとくぞう / Wikimedia Commons","license":"CC BY-SA 4.0","license_url":"https://creativecommons.org/licenses/by-sa/4.0/","source_url":"https://commons.wikimedia.org/wiki/File:Suginami_Museums-1.jpg","changes":"2018年撮影 · 縮小・WebP変換"}},
  {"names":["世田谷文学館"],"category":"museum","photo":{"url":"/place-photos/setagaya-literature.webp","credit":"江戸村のとくぞう / Wikimedia Commons","license":"CC BY-SA 4.0","license_url":"https://creativecommons.org/licenses/by-sa/4.0/","source_url":"https://commons.wikimedia.org/wiki/File:Setagaya_bungakukan_230113a.jpg","changes":"2023年撮影 · 縮小・WebP変換"}},
  {"names":["府中市美術館"],"category":"museum","photo":{"url":"/place-photos/fuchu-art.webp","credit":"Fuchu / Wikimedia Commons","license":"CC BY-SA 4.0","license_url":"https://creativecommons.org/licenses/by-sa/4.0/","source_url":"https://commons.wikimedia.org/wiki/File:Fuchu.art.museum.jpg","changes":"2016年撮影 · 縮小・WebP変換"}},
  {"names":["新宿区立新宿歴史博物館"],"category":"museum","photo":{"url":"/place-photos/shinjuku-history.webp","credit":"Suikotei / Wikimedia Commons","license":"CC BY 4.0","license_url":"https://creativecommons.org/licenses/by/4.0/","source_url":"https://commons.wikimedia.org/wiki/File:Shinjuku_Historical_Museum_20250713.jpg","changes":"2025年撮影 · 縮小・WebP変換"}},
  {"names":["すみだ郷土文化資料館"],"category":"museum","photo":{"url":"/place-photos/sumida-history.webp","credit":"遠枝 / Wikimedia Commons","license":"CC BY-SA 4.0","license_url":"https://creativecommons.org/licenses/by-sa/4.0/","source_url":"https://commons.wikimedia.org/wiki/File:%E3%81%99%E3%81%BF%E3%81%A0%E9%83%B7%E5%9C%9F%E6%96%87%E5%8C%96%E8%B3%87%E6%96%99%E9%A4%A8.jpg","changes":"2022年撮影 · 縮小・WebP変換"}},
  {"names":["葛飾区郷土と天文の博物館"],"category":"museum","photo":{"url":"/place-photos/katsushika-museum.webp","credit":"あばさー / Wikimedia Commons","license":"Public domain","license_url":"https://commons.wikimedia.org/wiki/Template:PD-self","source_url":"https://commons.wikimedia.org/wiki/File:Katsushika_City_Museum.JPG","changes":"2010年撮影 · 縮小・WebP変換"}},
  {"names":["府中市郷土の森博物館"],"category":"museum","photo":{"url":"/place-photos/fuchu-kyodo.webp","credit":"掬茶 / Wikimedia Commons","license":"CC BY-SA 3.0","license_url":"https://creativecommons.org/licenses/by-sa/3.0/","source_url":"https://commons.wikimedia.org/wiki/File:Fuchu_Municipal_Museum_in_the_Ky%C5%8Ddo-no-mori_Park_20130310-1.jpg","changes":"2013年撮影 · 縮小・WebP変換"}},
  {"names":["青梅市立美術館"],"category":"museum","photo":{"url":"/place-photos/ome-art.webp","credit":"あばさー / Wikimedia Commons","license":"Public domain","license_url":"https://commons.wikimedia.org/wiki/Template:PD-self","source_url":"https://commons.wikimedia.org/wiki/File:Ome_Municipal_Museum_of_Art.JPG","changes":"2016年撮影 · 縮小・WebP変換"}},
];

export function GET(request: NextRequest) {
  const name = (request.nextUrl.searchParams.get("name") || "").normalize("NFKC").trim();
  const category = request.nextUrl.searchParams.get("category");
  const match = photos.find(item => item.category === category && item.names.includes(name));
  return NextResponse.json({ photo: match?.photo || null }, {
    headers: { "Cache-Control": "public, max-age=3600" },
  });
}
