"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import maplibregl,{Map as MLMap} from "maplibre-gl";
type Place={id:number;name:string;category_slug:string;category_name:string;prefecture_name:string;municipality_name:string;address:string;longitude:number;latitude:number;official_url:string|null;data_date:string|null;aggregate_count?:number};
const cats=[{slug:"aquarium",name:"水族館",count:86,aliases:["水族館","アクアリウム","イルカ"]},{slug:"zoo",name:"動物園",count:91,aliases:["動物園","サファリ","どうぶつ"]},{slug:"roadside-station",name:"道の駅",count:1234,aliases:["道の駅","みちのえき"]},{slug:"airport",name:"空港",count:97,aliases:["空港","エアポート"]},{slug:"shelter",name:"避難場所",count:null,aliases:["避難場所","避難所","防災"]}];
export default function MapApp(){
 const node=useRef<HTMLDivElement>(null),map=useRef<MLMap|null>(null),placeIndex=useRef<Map<number,Place>>(new Map());
 const [places,setPlaces]=useState<Place[]>([]),[cat,setCat]=useState<string|null>(null),[prefecture,setPrefecture]=useState<string|null>(null),[selected,setSelected]=useState<Place|null>(null),[q,setQ]=useState(""),[loaded,setLoaded]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let alive=true;if(!cat){setPlaces([]);setLoaded(true);setNotice("");setError("");return()=>{alive=false}}setLoaded(false);setSelected(null);setError("");const qs=cat==="shelter"&&!prefecture?`category=shelter&summary=1`:`category=${encodeURIComponent(cat)}${prefecture?"&prefecture="+encodeURIComponent(prefecture):""}`;fetch(`/api/places?${qs}`).then(r=>r.json()).then(d=>{if(!alive)return;if(d.summary){setPlaces(d.summary.map((x:{prefecture_name:string;place_count:number;longitude:number;latitude:number},i:number)=>({id:-(i+1),name:x.prefecture_name,category_slug:"shelter",category_name:"指定緊急避難場所",prefecture_name:x.prefecture_name,municipality_name:"",address:"都道府県を選択すると地点を表示します",longitude:x.longitude,latitude:x.latitude,official_url:null,data_date:null,aggregate_count:Number(x.place_count)})))}else setPlaces(d.places||[]);setNotice(d.notice||"");setError(d.error||"");setLoaded(true)}).catch(()=>{if(alive){setPlaces([]);setError("データを取得できませんでした。時間をおいて再度お試しください。");setLoaded(true)}});return()=>{alive=false}},[cat,prefecture]);
 const normalizedQ=q.trim(); const shown=useMemo(()=>places.filter(p=>!normalizedQ||(`${p.name}${p.prefecture_name}${p.municipality_name}`).includes(normalizedQ)),[places,normalizedQ]); const categoryMatches=useMemo(()=>!cat&&normalizedQ?cats.filter(c=>c.aliases.some(a=>a.includes(normalizedQ)||normalizedQ.includes(a))):[],[cat,normalizedQ]);
 useEffect(()=>{placeIndex.current=new Map(places.map(p=>[p.id,p]));},[places]);
 const ranking=useMemo(()=>cat==="shelter"&&!prefecture?shown.map(p=>[p.prefecture_name,p.aggregate_count||0] as [string,number]).sort((a,b)=>b[1]-a[1]):Object.entries(shown.reduce<Record<string,number>>((a,p)=>{const n=p.prefecture_name||"地域未設定";a[n]=(a[n]||0)+1;return a;},{})).sort((a,b)=>b[1]-a[1]),[shown,cat,prefecture]);
 const total=useMemo(()=>cat==="shelter"&&!prefecture?shown.reduce((n,p)=>n+(p.aggregate_count||0),0):shown.length,[shown,cat,prefecture]);
 useEffect(()=>{if(!node.current||map.current)return;const m=new maplibregl.Map({container:node.current,style:"https://tiles.openfreemap.org/styles/liberty",center:[137.5,37.2],zoom:4.2});map.current=m;m.addControl(new maplibregl.NavigationControl({showCompass:false}),"bottom-right");m.on("load",()=>{m.addSource("places",{type:"geojson",data:{type:"FeatureCollection",features:[]},cluster:true,clusterMaxZoom:12,clusterRadius:45});m.addLayer({id:"clusters",type:"circle",source:"places",filter:["has","point_count"],paint:{"circle-radius":["step",["get","point_count"],18,100,24,1000,30],"circle-color":"#2563eb","circle-opacity":.86}});m.addLayer({id:"cluster-count",type:"symbol",source:"places",filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-size":12},paint:{"text-color":"#fff"}});m.addLayer({id:"unclustered",type:"circle",source:"places",filter:["!",["has","point_count"]],paint:{"circle-radius":6,"circle-color":"#2563eb","circle-stroke-width":2,"circle-stroke-color":"#fff"}});m.on("click","clusters",async e=>{const f=m.queryRenderedFeatures(e.point,{layers:["clusters"]})[0];if(!f)return;const src=m.getSource("places") as any;const z=await src.getClusterExpansionZoom(f.properties?.cluster_id);const a=(f.geometry as {coordinates:number[]}).coordinates;m.easeTo({center:[a[0],a[1]],zoom:z})});m.on("click","unclustered",e=>{const p=placeIndex.current.get(Number(e.features?.[0]?.properties?.id));if(!p)return;if(p.aggregate_count)setPrefecture(p.prefecture_name);else setSelected(p)});["clusters","unclustered"].forEach(id=>{m.on("mouseenter",id,()=>m.getCanvas().style.cursor="pointer");m.on("mouseleave",id,()=>m.getCanvas().style.cursor="")})});return()=>{m.remove();map.current=null}},[]);
 useEffect(()=>{const m=map.current;if(!m)return;const update=()=>{const src=m.getSource("places") as any;if(src)src.setData({type:"FeatureCollection",features:shown.map(p=>({type:"Feature",geometry:{type:"Point",coordinates:[p.longitude,p.latitude]},properties:{id:p.id}}))})};m.isStyleLoaded()?update():m.once("load",update)},[shown]);
 return <main className="shell"><header><div className="brand"><b>N</b><strong>にっぽんマップ</strong><small>BETA</small></div><span>日本の「どこ？」が、一目でわかる。</span></header><div className="workspace"><aside className="left"><p className="eyebrow">EXPLORE JAPAN</p><h1>日本の「どこ？」を<br/>地図で見つけよう。</h1><p className="lead">全国の施設・スポットを、分布から直感的に探せます。</p><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder={cat?"施設名・地域で絞り込み":"水族館、動物園、空港…"}/></div>{categoryMatches.length>0&&<div className="suggestions">{categoryMatches.map(c=><button key={c.slug} onClick={()=>{setCat(c.slug);setQ("");setPrefecture(null)}}>{c.name}を地図で見る →</button>)}</div>}<div className="chips">{cats.map(c=><button className={cat===c.slug?"active":""} onClick={()=>{setCat(c.slug);setPrefecture(null);setQ("")}} key={c.slug}><span>{c.name}</span><small>{c.count===null?"全国":c.count+"件"}</small></button>)}</div><div className="count"><span>{cat?"掲載データ":"カテゴリを選択"}</span><strong>{cat?(loaded?total:"—"):"—"}{cat&&<small>件</small>}</strong></div><div className="rank"><div><b>都道府県別</b><span>件数</span></div>{prefecture&&<button onClick={()=>setPrefecture(null)}><span>← 全国へ戻る</span><b>ALL</b></button>}{ranking.map(([n,v],i)=><button onClick={()=>setPrefecture(n)} key={n}><span><em>{String(i+1).padStart(2,"0")}</em>{n}</span><b>{v}</b></button>)}</div>{error&&<p className="error">{error}</p>}<p className="note">{notice||"公開データ・公式情報をもとに掲載しています。データの更新時点はカテゴリごとに異なります。"}</p></aside><section className="mapbox"><div ref={node} className="map"/><div className="label"><span>{cat?(cats.find(c=>c.slug===cat)?.name+(prefecture?" / "+prefecture:"")):"カテゴリを選ぶと地点を表示します"}</span><b>{cat?(loaded?total:"…")+" locations":"JAPAN"}</b></div></section><aside className="detail">{selected?<><button className="close" onClick={()=>setSelected(null)}>×</button><div className="visual">{selected.category_name}</div><p className="eyebrow">{selected.category_name}</p><h2>{selected.name}</h2><p>{selected.address}</p><div className="facts"><span>都道府県<b>{selected.prefecture_name||"—"}</b></span><span>市区町村<b>{selected.municipality_name||"—"}</b></span></div>{selected.official_url&&<a href={selected.official_url} target="_blank" rel="noreferrer">公式サイトを見る ↗</a>}<a href={`https://www.google.com/maps/search/?api=1&query=${selected.latitude},${selected.longitude}`} target="_blank" rel="noreferrer">Google Mapsで見る ↗</a>{selected.data_date&&<small>データ基準日：{selected.data_date}</small>}</>:<div className="empty"><b>⌖</b><h3>地点を選択</h3><p>地図上のポイントをクリックすると<br/>詳細情報が表示されます。</p></div>}</aside></div></main>;
}
